services:
  - type: web
    name: spps-ml-api
    env: python
    plan: free
    buildCommand: pip install -r ml-api/requirements.txt
    startCommand: uvicorn main:app --app-dir ml-api --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: spps-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: PORT
        value: 5000
      - key: ML_API_URL
        fromService:
          name: spps-ml-api
          type: web
          property: host
